pool: 
  name: "Default"

trigger:
  - main

steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: yes
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: '1.17'
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64   
      mavenDirectory: /opt/apache-maven-3.8.7/bin/mvn
    
